// tabla localizaciones

ALTER TABLE LOCATIONS ADD COLUMN `ISCLOSE` BIT(1) NOT NULL DEFAULT b'0'


ALTER TABLE CUSTOMERS ADD COLUMN `PROPERTIES` MEDIUMBLOB NULL

ALTER TABLE TICKETLINES ADD COLUMN `ID` VARCHAR(255) NULL DEFAULT NULL

ALTER TABLE STOCKCURRENT ADD COLUMN	`ID` VARCHAR(255) NULL DEFAULT NULL