SELECT P.* FROM RECEIPTS R
LEFT JOIN PAYMENTS P
ON P.RECEIPT = R.ID
LEFT JOIN TICKETS T
ON R.ID = T.ID
LEFT JOIN TICKETLINES TL
ON T.ID = TL.TICKET
LEFT JOIN CUSTOMERS c
on T.CUSTOMER = c.ID
WHERE c.NAME = 'carloscol'
ORDER BY R.DATENEW DESC, TL.LINE DESC


--CARLOSCOL EN NORDPOS:
'f3540d54-dc2e-4ab1-a099-41924368955d'


--CARLOSCOL EN OPENBRAVOPOS:
'c4c61f05-4985-4751-ae18-1cc9c31df3fc'


SELECT PP.*, RR.*, TT.*, TL.*, C.* FROM TICKETS TT
JOIN TICKETLINES TL
ON TL.TICKET = TT.TICKETID
JOIN RECEIPTS RR
ON TT.ID = RR.ID
JOIN PAYMENTS PP
ON PP.RECEIPT = RR.ID
LEFT JOIN CUSTOMERS C
ON C.ID = TT.CUSTOMER
ORDER BY RR.DATENEW DESC